const mdata = [
    {
        sort: "soft sandwich",
        banner: "soft_ban.jpg",
        product: [
            {
                name: "슈크림퐁당 샌드위치",
                image: "soft/soft1.png",
                descript: "달콤한 커스타드 크림에 바닐라빈이 콕콕~",
                info: "밀, 대두, 우유, 달걀 함유",
                new: "y",
                price: "2600",
            },
            {
                name: "오리지널 햄 샌드위치",
                image: "soft/soft2.png",
                descript: "스모키한 순수 돈육 햄의 진한 풍미가 가득!",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "치즈 샌드위치",
                image: "soft/soft3.png",
                descript: "체다 치즈와 버터크림의 부드러운 만남",
                info: "",
                new: "",
                price: "",
            },
            
            {
                name: "호밀빵 치즈 샌드위치",
                image: "soft/soft5.png",
                descript: "더 건강해진 호밀빵 치즈 샌드위치",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "호밀빵 햄 샌드위치",
                image: "soft/soft6.png",
                descript: "더 건강해진 호밀빵 햄 샌드위치",
                info: "",
                new: "",
                price: "",
            },
            
            {
                name: "딸기퐁당 샌드위치",
                image: "soft/soft8.png",
                descript: "딸기 크림 속 동결건조 딸기가 퐁당~",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "초코퐁당 샌드위치",
                image: "soft/soft9.png",
                descript: "깊고 진한 헤이즐넛 초코크림이 샌드위치에 퐁당! ",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "옥수수크림 샌드위치",
                image: "soft/soft10.png",
                descript: "더 부드럽고 고소해진 옥수수크림",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "쿠키앤크림 샌드위치",
                image: "soft/soft11.png",
                descript: "부드러운 우유크림 사이에 달콤바삭 쿠키가 듬뿍!",
                info: "",
                new: "y",
                price: "",
            },
        ],
    },
    {
        sort: "baked sandwich",
        banner: "baked_ban.jpg",
        product: [
            {
                name: "갓군샌 갈릭버터",
                image: "baked/baked1.png",
                descript: "고소한 버터와 국내산 마늘의 풍미 가득한 만남",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "갓군샌 트리플치즈",
                image: "baked/baked2.png",
                descript: "풍성하게 쌓아올린 3단 치즈의 갓!조합",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "갓군샌 눈꽃소보루",
                image: "baked/baked3.png",
                descript: "코코넛 소보루의 달콤함이 눈처럼 사르르",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "홍루이젠 잠봉뵈르",
                image: "baked/baked4.png",
                descript: "풍미 가득 버터와 국내산 잠봉이 만나 <br> 부드러운 소프트 바게트 속으로",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "바베큐 풀드포크",
                image: "baked/baked5.png",
                descript: "정통 아메리칸 풍미 바베큐 풀드포크",
                info: "",
                new: "y",
                price: "",
            },
        ],
    },
    {
        sort: "fresh sandwich",
        banner: "fresh_ban.jpg",
        product: [
            {
                name: "에그 맛살 샌드위치",
                image: "fresh/fresh1.png",
                descript: "꽃맛살과 부드러운 계란 샐러드의 든든한 조합",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "에그 참치마요 샌드위치",
                image: "fresh/fresh2.png",
                descript: "고소한 참치와 부드러운 계란 샐러드의 든든한 조합",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "에그 포테이토 샌드위치",
                image: "fresh/fresh3.png",
                descript: "감자와 에그 샐러드의 든든한 조합",
                info: "",
                new: "",
                price: "",
            },
        ],
    },
    {
        sort: "dessert",
        banner: "dessert_ban.jpg",
        product: [
            {
                name: "우유퐁당 케익샌드 초코",
                image: "dessert/dessert1.png",
                descript: "사르르 눈처럼 부드럽고 달콤한 <br> 우유크림 케익샌드 초코",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "우유퐁당 케익샌드 플레인",
                image: "dessert/dessert2.png",
                descript: "사르르 눈처럼 부드럽고 달콤한 <br> 우유크림 케익샌드 플레인",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "크로플",
                image: "dessert/dessert3.png",
                descript: "겉바속쫄! 버터향 가득 크로플",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "체다치즈 크로플",
                image: "dessert/dessert4.png",
                descript: "단짠단짠 체다치즈와 즐기는 크로플",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "마시멜로우 크로플",
                image: "dessert/dessert5.png",
                descript: "달콤한 마시멜로우와 즐기는 크로플",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "아이스크림 크로플",
                image: "dessert/dessert6.png",
                descript: "달콤한 아이스크림과 즐기는 크로플",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "에그롤",
                image: "dessert/dessert7.png",
                descript: "고소한 계란과 깊고 부드러운 버터향 가득",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "리얼펑리수",
                image: "dessert/dessert8.png",
                descript: "대만 현지 레시피를 완벽하게 구현한 <br> 프리미엄 파인애플 펑리수",
                info: "",
                new: "",
                price: "",
            },
        ],
    },
    {
        sort: "drink",
        banner: "drink_ban.jpg",
        product: [
            {
                name: "아메리카노",
                image: "drink/drink1.png",
                descript: "홍루이젠 고품질 원두의 풍미 가득",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "카페라떼",
                image: "drink/drink2.png",
                descript: "고소한 에스프레소에 부드러운 우유가 더해진 커피",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "카페 모카",
                image: "drink/drink3.png",
                descript: "초콜릿 풍미 가득한 카페 모카",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "바닐라 글레이즈드 라떼",
                image: "drink/drink4.png",
                descript: "흑당과 바닐라빈 시럽이 어우러진 부드러운 달콤함",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "멜론 소프트 라떼",
                image: "drink/drink5.png",
                descript: "달콤하고 부드러운 멜론라떼",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "딸기 소프트 라떼",
                image: "drink/drink6.png",
                descript: "달콤하고 부드러운 딸기라떼",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "레몬 에이드",
                image: "drink/drink7.png",
                descript: "상큼한 레몬과 탄산의 청량함을 함께 즐기는 에이드",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "자몽 에이드",
                image: "drink/drink8.png",
                descript: "달콤 쌉싸름한 자몽과 <br>탄산의 청량함을 함께 즐기는 에이드",
                info: "",
                new: "",
                price: "",
            },
            {
                name: "딸기 흑당버블티",
                image: "drink/drink9.png",
                descript: "흑당버블티에 상큼한 딸기과육이 듬뿍",
                info: "",
                new: "y",
                price: "",
            },
            {
                name: "청포도 아이스티",
                image: "drink/drink10.png",
                descript: "청량함을 담은 상큼달콤 청포도 아이스티",
                info: "",
                new: "y",
                price: "",
            },
        ],
    },
]; /// mdata ///
